make entries with legacy class names backwards compatible
scullxbones/pekko-persistence-mongo pull request #14
Opened 2023-08-31 21:11 UTC by bdoyle0182

2023-08-31 21:14 UTC, pjfanning commented on scala/src/main/scala/pekko/contrib/persistence/mongodb/MongoDataModel.scala
> +    val backwardsCompatClazz = loadClass.getClassFor[X forSome { type X <: AnyRef }](className.replace("akka", "org.apache.pekko"))
Can you make this a def? Then it only runs if needed.

2023-09-01 10:20 UTC, thjaeckle commented on scala/src/main/scala/pekko/contrib/persistence/mongodb/MongoDataModel.scala
> +    def backwardsCompatClazz = loadClass.getClassFor[X forSome { type X <: AnyRef }](className.replace("akka", "org.apache.pekko"))
`className.replace("akka", "org.apache.pekko")` would replace any occurrences of `akka` ... 
Couldn't we check for `startsWith("akka.")` and if the class starts with "akka." - only then replace the first occurrence using `replaceFirst(regex, "org.apache.pekko")` with `org.apache.pekko`?

2023-09-01 10:21 UTC, thjaeckle requested changes
I would adjust the replacement of "akka" in classnames to make it more bulletproof

2023-09-01 16:59 UTC, bdoyle0182 commented
I cleaned it up and followed your suggestion good catch there to replaceFirst. I also realized we need to backport this to the old plugin to support roll backs, see this comment on the issue https://github.com/scullxbones/pekko-persistence-mongo/issues/10

2023-09-04 09:42 UTC, thjaeckle approved these changes

2023-09-04 09:42 UTC, merged

2023-09-04 09:42 UTC, thjaeckle commented
Thanks for the contribution @bdoyle0182 👍 
Will release a `1.0.2` containing this fix.

2023-12-08 13:04 UTC, SakulK commented
PSA for anyone that might hit the same issue as me: this fix unfortunately doesn't seem to address a similar issue with `PersistentFSM` snapshots. Here is the interesting part of the stacktrace that shows up in logs:
```
java.util.NoSuchElementException: None.get
     at scala.None$.get(Option.scala:627)
     at scala.None$.get(Option.scala:626)
     at pekko.contrib.persistence.mongodb.driver.ScalaDriverPersistenceSnapshotter$.deserializeSnapshot(ScalaDriverPersistenceSnapshotter.scala:43)
     at pekko.contrib.persistence.mongodb.driver.ScalaDriverPersistenceSnapshotter.$anonfun$findYoungestSnapshotByMaxSequence$5(ScalaDriverPersistenceSnapshotter.scala:82)
```
After digging deeper I found out that `deserialize` call here:
https://github.com/scullxbones/pekko-persistence-mongo/blob/b8127da3598eab0581d4f77cfc57b5c4b4ba6809/scala/src/main/scala/pekko/contrib/persistence/mongodb/driver/ScalaDriverPersistenceSnapshotter.scala#L44
returns:
```
Failure(java.io.NotSerializableException: Cannot find manifest class [akka.persistence.fsm.PersistentFSM$PersistentFSMSnapshot] for serializer with id [7].)
```
Which is thrown from https://github.com/apache/incubator-pekko/blob/main/actor/src/main/scala/org/apache/pekko/serialization/Serialization.scala#L246
I will share a workaround if I find one :wink:

2023-12-08 14:07 UTC, SakulK commented
Ok, a hacky workaround that I came up with:
1. Make a copy of `org.apache.pekko.persistence.serialization.SnapshotSerializer` class from pekko persistence (here called `CustomSnapshotSerializer`)
2. In `snapshotFromBinary` replace the last line with:
```scala
    serialization
      .deserialize(snapshotBytes, serializerId, manifest)
      .recover {
        case _: NotSerializableException if manifest.startsWith("akka") =>
          serialization.deserialize(snapshotBytes, serializerId, manifest.replaceFirst("akka", "org.apache.pekko"))
      }
      .get
```
3. Register the serializer in the config, something like this:
```
pekko.actor {
  serialization-identifiers {
    "org.apache.pekko.persistence.serialization.SnapshotSerializer" = -8
    "org.apache.pekko.persistence.serialization.CustomSnapshotSerializer" = 8
  }
  serializers.customSnapshotSerializer = "org.apache.pekko.persistence.serialization.CustomSnapshotSerializer"
  serialization-bindings {
    "org.apache.pekko.persistence.serialization.Snapshot" = customSnapshotSerializer
  }
}
```
I'm not sure if it makes sense to propose the change from point 2. to the main pekko repo :thinking: